name: mineral_cache
description: Cache for the Mineral framework.
version: 1.0.0-dev.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.0

# Add regular dependencies here.
dependencies:
  mineral: ^4.0.0-dev.2
  redis: ^4.0.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
