name: mineral_cache
description: Cache for the Mineral framework.
version: 1.0.0-dev.3
repository: https://github.com/mineral-dart/cache

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  mineral: ^4.0.0-dev.6
  redis: ^4.0.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
